//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konstantinova41
{
    using System;
    using System.Collections.Generic;
    
    public partial class PicupPoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PicupPoint()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int PicUpPointID { get; set; }
        public int PicUpPointIndex { get; set; }
        public string PicUpPointCity { get; set; }
        public string PicUpPointStreet { get; set; }
        public int PicUpPointHouse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
